### ISSUE TITLE
default-import: Set minimal node version is breaking change 

### ISSUE THREAD

**Issue by ivanmjartan** [JacobLey/leyman#1]
Just for your info when you increasing or set minimal version of node its breaking change and when clients reference package via ^ it could break CI jobs action etc.  Like happened in now in version 1.1.6

**Comment by JacobLey** [comment]
Thanks for the heads up, that was not an intentional break for consumers.
I just blindly bumped to my local testing level.

There seems to be competing views about whether or not engines counts as a major bump: 
For - https://stackoverflow.com/questions/66282951/semver-policy-with-node-js-engine-enforcing
Against - https://rtpg.co/2023/09/27/avoiding-major-version-bumps-for-node/

But I think I can align that since clients _could_ experience a break here, it _should_ be marked as breaking.

I've released a small [1.1.7](https://www.npmjs.com/package/default-import/v/1.1.7) that reverts the engine requirements, so the `^` approach should no longer be broken.

I have also released a [2.0.1](https://www.npmjs.com/package/default-import/v/2.0.1) which restricts engines to current active version (since that is the only versions I actually test on and can guarantee behavior).
That also includes a fix to include npmignore 🤦 , and will be the development target going forward for the `default-import` package.

Not that I realistically forsee lots of development on that package besides minor support bumps going forward. It is a very small package.
